[package]
name = "brawllib_rs"
version = "0.1.0"
authors = ["Rukai <rubickent@gmail.com>"]

[dependencies]
byteorder = "1"
bitflags = "1"
cgmath = { version = "0.16", features = ["mint"] }
log = "0.4"

[dev-dependencies]
getopts = "0.2"
three = { git = "https://github.com/three-rs/three" }
mint = "0.5"

[profile.release]
debug = true
