[package]
name = "brawllib_rs"
version = "0.1.0"
authors = ["Rukai <rubickent@gmail.com>"]

[dependencies]
bitflags = "1"
byteorder = "1"
cgmath = { version = "0.16", features = ["mint", "serde"] }
log = "0.4"
serde = "1"
serde_derive = "1"

[dev-dependencies]
getopts = "0.2"
three = { git = "https://github.com/three-rs/three" }
mint = "0.5"

[profile.release]
debug = true
