[package]
name = "brawllib_rs"
version = "0.1.0"
authors = ["Rukai <rubickent@gmail.com>"]

[dependencies]
byteorder = "1"
bitflags = "1"
cgmath = "0.16"
log = "0.4"

[dev-dependencies]
getopts = "0.2"
