[package]
name = "brawllib_rs"
edition = "2018"
version = "0.1.2"
authors = ["Rukai <rubickent@gmail.com>"]
description = "Brawl character file parser, based on brawlbox/brawllib"
license = "MIT"
repository = "https://github.com/rukai/brawllib_rs"
keywords = ["super", "smash", "bros", "brawl", "lib"]
categories = ["games", "game-engines"]

[dependencies]
bitflags = "1"
byteorder = "1"
cgmath = { version = "0.16", features = ["mint", "serde"] }
log = "0.4"
serde = "1"
serde_derive = "1"
rayon = "1"

[dev-dependencies]
getopts = "0.2"
three = "0.4"
mint = "0.5"

[profile.release]
debug = true
